// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RegisterRequest, RegisterResponse } from "./auth_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service auth.Auth
 */
export const Auth = {
  typeName: "auth.Auth",
  methods: {
    /**
     * @generated from rpc auth.Auth.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.Auth.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

